In [0]:
import numpy as np
import pandas as pd

In [0]:
data=pd.read_csv('C:\\Users\\kc\\Downloads\\data1.csv',header=None)
#print(data)
label=pd.read_csv('C:\\Users\\kc\\Downloads\\label1.csv',header=None)
#print(label)
#Dimension of the data array.
print(data.shape)
#ans:Because it is a matrix of 20000*20
#ans:Each row signifies a  datapoint or the value of each feature of every house.

(20000, 20)


In [0]:
#2. Similarly extract training labels from label1.csv to Numpy array. What is the shape/dimension of Numpy Array? Also, convert each scalar value of output into one-hot vector. As for example: 1should get converted [0,1,0,0,0], 4 should get converted to [0,0,0,0,1] and so on. What is the shape of converted Numpy array?

In [0]:
#coverting data and label to array
npdata=np.asarray(data)
nplabel=np.asarray(label)
#conversion of array to one-hotDash vector form
n_values = np.max((nplabel))+1
print(n_values)  
oneHotDash=np.eye(n_values)[nplabel]
oneHotDash=np.reshape(oneHotDash,(20000,5))
print(oneHotDash)
print(npdata.shape)
print(nplabel.shape)
print(oneHot.shape)


5
[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
(20000, 20)
(20000, 1)


NameError: name 'oneHot' is not defined

In [0]:
from sklearn.model_selection import train_test_split
trainData,testDataDash=train_test_split(npdata,train_size=0.8,test_size=0.2,shuffle=False)#divide data in a 80:20 ratio
trainlabel,testLabelDash=train_test_split(oneHotDash,train_size=0.8,test_size=0.2,shuffle=False)


In [0]:
validateData, testData=train_test_split(testDataDash,train_size=0.5,test_size=0.5,shuffle=False)#dividing rest20% data half half in validation and testing data
validateLabel, testLabel=train_test_split(testLabelDash,train_size=0.5,test_size=0.5,shuffle=False)

In [0]:
print(trainData.shape)
print(validateData.shape)
print(testData.shape)
print(trainData.size)
print(validateLabel.shape)
print(testLabelDash.shape)

(16000, 20)
(2000, 20)
(2000, 20)
320000
(2000, 5)
(4000, 5)


In [0]:
h=input()#number of neurons in the hidden layer
h=int(h)

20


In [0]:
std1=(1/np.sqrt(20))#standard deviation of initialiing first weights
std2=(1/np.sqrt(h))#standard deviation of initialiing second weights
w1=np.random.normal(0,std1,(20,h))#gaussian random assignment of weight
w2=np.random.normal(0,std2,(h,5))#gaussian random assignment of weights 
#print("std1\n",std1,"std2\n",std2)
print("w1\n",w1)
print("w2\n",w2)
print(w1.shape)
print(w2.shape)

w1
 [[-0.24047004  0.2873567   0.03424772  0.20379815 -0.05202134 -0.19585229
  -0.04891052 -0.12620258  0.31774368  0.17085183  0.15995675  0.13161725
  -0.15557189 -0.3980376   0.3881237  -0.02299794 -0.39359078  0.09676945
  -0.1685601  -0.04712996]
 [-0.21432815  0.14787484  0.20166766  0.09998479 -0.24544886  0.06249916
  -0.30743492 -0.11602656  0.64494331  0.03310243  0.0868487  -0.12982229
   0.34865411  0.01696914  0.09909292  0.23088986 -0.00787634  0.00771868
   0.12214015 -0.23686298]
 [-0.21528324  0.04691262 -0.07344418 -0.17039626  0.29988912 -0.43396045
  -0.16520983  0.20849269 -0.08518573 -0.38416799  0.37647451 -0.0164777
   0.17407565 -0.05423136 -0.2444788  -0.27089613 -0.15977255 -0.29567861
   0.40192944  0.05504289]
 [-0.11526222 -0.02074273  0.05481917 -0.26753793 -0.18059968 -0.01838699
   0.02979543 -0.05551955  0.51108649 -0.08254788  0.41730867  0.0415106
   0.2900466   0.12484195 -0.13791823 -0.40961131  0.27917377 -0.18658602
  -0.06306851 -0.18228845]
 [

In [0]:
b1=np.zeros(h)
b2=np.zeros(5)
print(b1)
print(b2)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [0]:
#Implement feedforward function of Neural Network. At output layer and hidden layer, implement
#Activation function (any of the 4 activation functions). Calculate the final output from the output
#layer. What is the shape of the output ?

In [0]:
def actFunc(haha,choose):
    if choose==1:#Sigmoid
        return (1/(1+np.exp(-haha)))
    elif choose==2:#ReLU
        return (np.max(0,haha))
    elif choose==3:#tanh
        return (np.tanh(haha))
    elif choose==4:#SoftMax
        temp=np.exp(haha)
        return temp/np.sum(temp,axis=1,keepdims=True) 
    

In [0]:
def forwardFunc(npData):
    a0=npData
    z1=np.dot(a0,w1)+b1
    a1=actFunc(z1,3)
    z2=np.dot(a1,w2)+b2
    a2=actFunc(z2,4) 
    return a0,z1,a1,z2,a2

# Backward pass


In [0]:
epochs=int(input())

batch=int(input())

200
1600


In [0]:
alpha=0.001

In [0]:
def costFunc(y,t):
    return -(t*(np.log(y))+(1-t)*np.log(1-y))

In [0]:
def accuracyFunc(output,labelData,dataSize):
    maxInRow=np.argmax(output, axis=1)
    maxInLabels=np.argmax(labelData, axis=1)
    huehue=np.equal(maxInRow,maxInLabels)
    count=np.sum(huehue)
 
    return (count/dataSize)*100

In [0]:
print(trainData.shape)
print(trainData[0].shape)

(16000, 20)
(20,)


In [0]:
for j in range(epochs):
    for i in range(int(16000/batch)):
        a0,z1,a1,z2,a2=forwardFunc(trainData[i*batch:(i+1)*batch,:])
        y=a2
        labelbatch=trainlabel[i*batch:(i+1)*batch,:]
        #backwardPass
        del2=y-labelbatch

        #del1=np.dot(del2,w2.T)*(1-pow(actFunc(z1,3),2))
        #dcdw2=y-labelbatch
        del1=np.dot(del2,w2.T)*(1-pow(actFunc(z1,3),2))
        dcdw2=np.dot(a1.T,del2)
        dcdw1=np.dot(a0.T,del1)
        dcdb2=np.sum(del2,axis=0)
        dcdb1=np.sum(del1,axis=0)
        w1=w1-alpha*dcdw1
        w2=w2-alpha*dcdw2
        b2=b2-alpha*dcdb2
        b1=b1-alpha*dcdb1
    a0,z1,a1,z2,a2=forwardFunc(trainData)
    ytrue=a2
    cost=np.sum(costFunc(ytrue,trainlabel))/16000
    print ("cost=",end="")
    print (cost)
    accuracy = accuracyFunc(ytrue,trainlabel,16000.0)
    print("training accuracy =",end="")
    print (accuracy)
    #validation accuracy
va0,vz1,va1,vz2,va2=forwardFunc(validateData)
vOutput=va2
accuracy = accuracyFunc(vOutput,validateLabel,2000.0)
print ("validation accuracy")
print (accuracy)

        

cost=0.6877970533320957
training accuracy =86.80624999999999
cost=0.6740285087378052
training accuracy =87.09375
cost=0.6615293394545694
training accuracy =87.23125
cost=0.6498711692413204
training accuracy =87.52499999999999
cost=0.638901709796837
training accuracy =87.7
cost=0.6285123151980148
training accuracy =87.9625
cost=0.6186138390595762
training accuracy =88.14999999999999
cost=0.6091524437953924
training accuracy =88.3125
cost=0.6001297712563797
training accuracy =88.46875
cost=0.5916192807934236
training accuracy =88.60625
cost=0.58368641032939
training accuracy =88.775
cost=0.576323565068057
training accuracy =88.91250000000001
cost=0.5694767152404238
training accuracy =89.08125
cost=0.5630892589552478
training accuracy =89.2625
cost=0.557120219159253
training accuracy =89.4375
cost=0.5515439570945666
training accuracy =89.60000000000001
cost=0.5463434125208656
training accuracy =89.71875
cost=0.5415035151386537
training accuracy =89.8375
cost=0.5370072619936043
training ac

cost=0.44348094433770757
training accuracy =92.08125
cost=0.44336621395603093
training accuracy =92.06875
cost=0.4432516514976571
training accuracy =92.09375
cost=0.4431372053938302
training accuracy =92.11875
cost=0.4430228243065008
training accuracy =92.125
cost=0.44290845770168097
training accuracy =92.13125
cost=0.442794056412332
training accuracy =92.13125
cost=0.4426795731546395
training accuracy =92.15
cost=0.4425649629669208
training accuracy =92.13125
cost=0.4424501835492704
training accuracy =92.1375
cost=0.4423351954936725
training accuracy =92.14375
cost=0.44221996240774264
training accuracy =92.15
cost=0.4421044509494536
training accuracy =92.13125
cost=0.4419886308040533
training accuracy =92.13125
cost=0.44187247464693324
training accuracy =92.14375
cost=0.44175595814660346
training accuracy =92.14375
cost=0.441639060069544
training accuracy =92.1375
cost=0.44152176255300185
training accuracy =92.13125
cost=0.44140405161242124
training accuracy =92.1375
cost=0.4412859179